# Ejercicios Numpy Arrays

1. Crear un array unidimensional a partir de una lista de enteros [1, 2, 3, 4, 5] y mostrar sus propiedades: forma, número de dimensiones y tamaño.


In [1]:
import numpy as np

listaEnteros = np.array([range(1,6)])
print(f"Forma -> {listaEnteros.shape}")
print(f"Numero dimensiones -> {listaEnteros.ndim}")
print(f"Tamaño -> {listaEnteros.size}")

Forma -> (1, 5)
Numero dimensiones -> 2
Tamaño -> 5


2. Crear un array de ceros de longitud 5 y mostrarlo en pantalla.


In [2]:
arrayCeros = np.zeros(5)
print(arrayCeros)

[0. 0. 0. 0. 0.]


3. Utilizar np.arange() para crear un array que contenga los números del 10 al 19 y mostrarlo.


In [3]:
array = np.arange(10,20)
print(array)

[10 11 12 13 14 15 16 17 18 19]


4. Crear un array de 5 elementos equiespaciados entre 0 y 1 y mostrar el resultado.


In [4]:
array = np.linspace(start=0,stop=1,num=5)
print(array)

[0.   0.25 0.5  0.75 1.  ]


5. Dado el array arr = np.array([1, 2, 3.5, 4.7]), imprimir el tipo de dato de sus elementos.

In [5]:
arr = np.array([1,2,3.5,4.7])
print(arr.dtype)

float64


6. Crear un array de enteros aleatorios de tamaño 10 con valores entre 10 y 50. Luego, invertir el array (es decir, revertir el orden de los elementos) y mostrar ambos arrays.


In [6]:
arr = np.random.randint(10,50,size=10)
print(arr)

[20 45 39 24 30 14 43 14 26 31]


7. Dados los arrays a = np.array([1, 2, 3]) y b = np.array([4, 5, 6]), realizar las operaciones de suma, resta y multiplicación elemento a elemento, y mostrar los resultados.


In [7]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])

print(f"Suma = {a+b}")
print(f"Resta = {a-b}")
print(f"Multiplicación = {a*b}")

Suma = [5 7 9]
Resta = [-3 -3 -3]
Multiplicación = [ 4 10 18]


8. Crear un array de 10 números aleatorios entre 0 y 100. Luego, filtrar y mostrar todos los elementos que sean mayores que 50.


In [8]:
arr = np.random.randint(10,100,size=10)
print(arr[arr > 50])

[86 60 89 51 67 95 69]


9. Dados los arrays a = np.array([1, 2, 3, 4]) y b = np.array([5, 6, 7, 8]), concatenarlos y mostrar el resultado.


In [9]:
a = np.array([1, 2, 3, 4]) 
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)))

[1 2 3 4 5 6 7 8]


10. Dado el array arr = np.array([15, 22, 14, 39, 56, 78, 12, 23]), encontrar y mostrar los índices de los elementos que son múltiplos de 3.


In [10]:
arr = np.array([15, 22, 14, 39, 56, 78, 12, 23])
print(np.nonzero(arr % 3 == 0))

(array([0, 3, 5, 6]),)


11. Escribir una función que reciba una lista de números con tipos de datos mixtos (enteros y flotantes), y devuelva un array de NumPy con tipo de dato float64 sin perder información. Mostrar el array resultante y su tipo.


In [11]:
def transformList(lista):
    return np.array(lista,dtype=float)

listaTransformada = transformList([1,2,3,4.5,6.9,6])
print(listaTransformada)
print(listaTransformada.dtype)

[1.  2.  3.  4.5 6.9 6. ]
float64


12. Dado el array arr = np.array([1, 3, 3, 3, 6, 2, 3, 5]), eliminar los elementos duplicados, ordenar el array resultante y mostrarlo.


In [12]:
arr = np.array([1, 3, 3, 3, 6, 2, 3, 5])
arr.sort()
arr = np.unique(ar=arr)

print(arr)

[1 2 3 5 6]


13. Crear un array de 20 números enteros aleatorios entre 0 y 100. Reemplazar todos los elementos que sean múltiplos de 3 por el valor -1, utilizando indexación avanzada. Mostrar el array resultante.


In [13]:
arr = np.random.randint(0,100,size=20)
print(f"Antes -> {arr}")
index = np.nonzero(arr % 3 == 0)
arr = np.delete(arr,index)
print(f"Despues -> {arr}")

Antes -> [76 78  0 21 81 58 25 43 81 35 49 23 62  2 77 58 32 78 32 31]
Despues -> [76 58 25 43 35 49 23 62  2 77 58 32 32 31]


14. Dado un array de números enteros aleatorios de tamaño 15, calcular y mostrar la media, mediana y desviación estándar de los elementos.


In [14]:
arr = np.random.randint(100,size=15)
print(arr)
print(f"Media = {np.mean(arr)}")
print(f"Mediana = {np.median(arr)}")
print(f"Desviación estandard = {np.std(arr)}")

[48 95 75 96 40 38 66 54  7 45 93 70 76 20 68]
Media = 59.4
Mediana = 66.0
Desviación estandard = 25.798707977984737


15. Implementar una función que reciba un array unidimensional y un entero n, y devuelva el array original desplazado n posiciones a la derecha (los elementos desplazados deben reaparecer al inicio). Mostrar el array original y el array desplazado. Por ejemplo:
    
Array original: [1 2 3 4 5 6 7 8 9]
Número: 3
Array desplazado: [7 8 9 1 2 3 4 5 6]

In [15]:
def desplazarN(arr,n):
    return np.roll(arr,n)
    


arr = range(9)

print(desplazarN(arr,5))

[4 5 6 7 8 0 1 2 3]


16. Dado un array de 10 números aleatorios, normalizar el array de forma que sus valores estén entre 0 y 1. Mostrar el array original y el array normalizado.


In [16]:
arr = np.random.randint(0,100,size=10)
maximo = np.max(arr)
arrNormalizado = arr/maximo
print(arr)
print(arrNormalizado)

[95 30 13 37 89 65 93 65  3  8]
[1.         0.31578947 0.13684211 0.38947368 0.93684211 0.68421053
 0.97894737 0.68421053 0.03157895 0.08421053]


17. Generar un array de 20 números enteros aleatorios entre 1 y 100. Ordenar el array en orden descendente y mostrar el resultado.


In [17]:
arr = np.random.randint(1,100,size=20)
arr = np.sort(arr)[::-1]
print(arr)

[95 93 89 88 75 60 51 47 46 44 35 26 18 10  7  6  6  5  4  1]


18. Dado un array, crear una función que devuelva un nuevo array donde cada elemento sea el producto de todos los elementos del array original excepto el elemento actual, sin utilizar bucles. Mostrar el array original y el array resultante. Por ejemplo:

Array original: [1 2 3 4]
Array resultante: [24 12 8 6]

In [18]:
def calcularProducto(arr):
    multiplicar = np.prod(arr) 
    return multiplicar / arr 
    
arr = [1,2,3,4]
print(f"Original : {arr}")
print(f"Destino : {calcularProducto(arr)}")


Original : [1, 2, 3, 4]
Destino : [24. 12.  8.  6.]


19. Dado un array de números enteros, contar el número de elementos únicos y mostrar el resultado.


In [19]:
arr = np.random.randint(10,20,size=1000)
arr = np.unique(arr)
print(f"Valores unicos {arr}")
print(f"Cantidad de unicos {arr.size}")

Valores unicos [10 11 12 13 14 15 16 17 18 19]
Cantidad de unicos 10


20. Crear un array de 10 números aleatorios entre 0 y 50. Calcular y mostrar el valor acumulado de la suma de sus elementos. Por ejemplo: 
    
Array original: [12  7 25 34 10  3 47 20  5 41]
Valor acumulado de la suma: [ 12  19  44  78  88  91 138 158 163 204]

In [20]:
arr = np.random.randint(50,size=10)

print(np.cumsum(arr))

[ 19  40  54  64  84 125 151 165 207 212]


# Ejercicios Numpy Matrices

1. Crear una matriz de 3 filas y 2 columnas a partir de la lista de listas [[7, 22], [15, 46], [9, 11]] utilizando np.array(). Mostrar la matriz resultante y sus propiedades (forma, número de dimensiones, tamaño y tipo de dato).

In [24]:
matriz = np.array([[7, 22], [15, 46], [9, 11]])

print(matriz)
print(f"Forma -> {matriz.shape}")
print(f"Tamaño -> {matriz.size}")
print(f"Tipo dato -> {matriz.dtype}")

[[ 7 22]
 [15 46]
 [ 9 11]]
Forma -> (3, 2)
Tamaño -> 6
Tipo dato -> int64



2. Crear una matriz de 3x3 llena de ceros utilizando np.zeros().Crear una matriz de 2x2 llena de unos utilizando np.ones(). Crear una matriz de 4x3 con valores aleatorios entre 0 y 1 utilizando np.random.random(). Mostrar todas las matrices creadas.

In [27]:
matriz3 = np.zeros([3,3])
print(matriz3)
matriz2 = np.ones([2,2])
print(matriz2)
matrizRandom = np.random.random([4,3])
print(matrizRandom)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[[0.95934087 0.33002807 0.47903535]
 [0.84273002 0.94461236 0.25974296]
 [0.62577127 0.8712716  0.43874311]
 [0.66999458 0.16748095 0.89224384]]



3. Dada la matriz matriz = np.array([[7, 22], [15, 46], [9, 11]]):
   - Acceder y mostrar el elemento ubicado en la segunda fila y primera columna.
   - Acceder y mostrar el último elemento de la primera fila utilizando índices negativos.

In [30]:
matriz = np.array([[7, 22], [15, 46], [9, 11]])

elemento = matriz[1][0]
print(elemento)
elemento = matriz[0][-1]
print(elemento)

15
22



4. Dada la matriz matriz = np.array([[7, 22], [15, 46], [9, 11]])
   - Seleccionar y mostrar las filas 1 y 2.
   - Seleccionar y mostrar la primera columna de las dos primeras filas.

In [45]:
matriz = np.array([[7, 22], [15, 46], [9, 11]])
print(matriz[[1,2]])
print()
print(matriz[0:2,0])

[[15 46]
 [ 9 11]]

[ 7 15]


5. Crear una matriz de 3x4 con números enteros aleatorios entre 0 y 10. Seleccionar y mostrar todos los elementos que sean menores que 5 utilizando indexación booleana.


In [49]:
matriz = np.random.randint(10,size=[3,4])
print(matriz)
print()
print(matriz[matriz < 5 ])

[[9 7 2 9]
 [0 9 0 9]
 [8 6 6 4]]

[2 0 0 4]


6. Crear una matriz de 2x6 con números enteros aleatorios entre 1 y 12. Remodelar esta matriz a una forma de 3x4.Mostrar ambas matrices (original y remodelada).


In [53]:
matriz = np.random.randint(1,12,size=[2,6])
print(f"Original \n{matriz}")
matriz = matriz.reshape([3,4])
print(f"Destino \n{matriz}")


Original 
[[ 2  9 10  2  4 10]
 [ 7  4  2  5 10 10]]
Destino 
[[ 2  9 10  2]
 [ 4 10  7  4]
 [ 2  5 10 10]]



7. Dadas las matrices matriz_a = np.array([[7, 22], [15, 46]]) |  matriz_b = np.array([[1, 1], [1, 1]]), Realizar y mostrar:
   - La suma de matriz_a y matriz_b.
   - La resta de matriz_a y matriz_b.
   - La multiplicación elemento a elemento de matriz_a y matriz_b.:

In [54]:
matriz_a = np.array([[7, 22], [15, 46]]) 
matriz_b = np.array([[1, 1], [1, 1]])


print(f"Suma = {matriz_a+matriz_b}")
print(f"Resta = {matriz_a-matriz_b}")
print(f"Multiplicación = {matriz_a*matriz_b}")

Suma = [[ 8 23]
 [16 47]]
Resta = [[ 6 21]
 [14 45]]
Multiplicación = [[ 7 22]
 [15 46]]


8.  Crear una matriz de 3x4 con números enteros aleatorios entre 0 y 10. Seleccionar y mostrar todos los elementos que sean mayores que 2 y menores que 7 utilizando operadores lógicos.


In [62]:
matriz = np.random.randint(10,size=[3,4])
print(matriz[(matriz > 2) & (matriz < 7) ])

[5 4 5 5]


9.  Dadas las matrices a = np.array([1, 2, 3, 4]) | b = np.array([5, 6, 7, 8]), Concatenar ambas matrices en una sola matriz de 8 elementos y mostrar el resultado.


In [64]:
a = np.array([1, 2, 3, 4]) 
b = np.array([5, 6, 7, 8])

print(np.concatenate([a,b]))

[1 2 3 4 5 6 7 8]


10. Dada la matriz matriz = np.random.randint(10, 51, size=(4, 5)), encontrar y mostrar los índices de los elementos que son múltiplos de 3.


In [67]:
matriz = np.random.randint(10, 51, size=(4, 5))
print(matriz)
print(np.nonzero(matriz % 3 == 0))

[[34 47 15 11 49]
 [10 13 14 28 42]
 [34 27 39 15 25]
 [46 37 29 13 35]]
(array([0, 1, 2, 2, 2]), array([2, 4, 1, 2, 3]))


11. Crear una matriz de 4x5 con números enteros aleatorios entre 1 y 20.Calcular y mostrar:
    - La suma de todos los elementos de la matriz.
    - El producto de todos los elementos de la matriz.

In [73]:
matriz = np.random.randint(1,20,size=[4,5])
print(matriz)
print(np.sum(matriz))
print(np.prod(matriz))

[[16  6 19  8 14]
 [13 16  9  8 14]
 [10 17  5 16  3]
 [18 15 18 16  6]]
247
3675075569722064896


12. Dada la matriz matriz = np.array([[1, 2, 3], [4, 5, 6]])
    - Transponer la matriz y mostrar la matriz transpuesta.
    - Verificar que la forma de la matriz transpuesta es correcta.


In [76]:
matriz = np.array([[1, 2, 3], [4, 5, 6]])

matriz = np.transpose(matriz)
print(matriz)
print(matriz.shape)

[[1 4]
 [2 5]
 [3 6]]
(3, 2)


13. Crear dos matrices compatibles para multiplicación. Implementar la multiplicación matricial sin utilizar la función np.dot() ni el operador @. Mostrar las matrices originales y el resultado de la multiplicación.

In [80]:
def multiplicacionMatricial(m1,m2):
    if m1.shape[1] != m2.shape[0]:
        return "Las matrices no son compatibles para multiplicación"
    
    filas = m1.shape[0]
    columnas = m2.shape[1]
    comun = m1.shape[1]
    
    resultado = np.zeros((filas, columnas))
    
    for fila in range(filas):
        for columna in range(columnas):
            for c in range(comun):
                resultado[fila][columna] += m1[fila][c] * m2[c][columna]
                
    return f"El resultado de la multiplicación es {resultado}"
    
    

matriz = np.random.randint(10,size=[2,2])
matriz2 = np.random.randint(10,size=[2,2])

print(multiplicacionMatricial(matriz,matriz2))

El resultado de la multiplicación es [[28. 11.]
 [12. 24.]]


14. Crear una matriz de 3x4 con números enteros aleatorios entre 1 y 100. Normalizar la matriz de forma que sus valores estén entre 0 y 1. Mostrar la matriz original y la matriz normalizada.


In [81]:
matriz = np.random.randint(1,100,size=[3,4])

maximo = matriz.max()
print(matriz / maximo)

[[0.2967033  0.12087912 1.         0.25274725]
 [0.92307692 0.54945055 0.3956044  0.7032967 ]
 [0.12087912 0.53846154 0.48351648 0.16483516]]


15. Implementar una función que reciba una matriz bidimensional y un entero n, y devuelva la matriz desplazada n filas hacia la derecha. Las filas desplazadas deben reaparecer al inicio. Mostrar la matriz original y la matriz desplazada. Ejemplo de salida:
    
    Matriz original:
    [[ 1  2  3]
    [ 4  5  6]
    [ 7  8  9]]

    Matriz desplazada 1 fila a la derecha:
    [[7 8 9]
    [1 2 3]
    [4 5 6]]

In [ ]:
def rollMatriz(matriz,n):
    return np.roll(matriz,n,axis=0)

matriz = np.arange(1,10).reshape(3,3)
print(f"Matriz original \n{matriz}")
print(f"Matriz desplazada \n{rollMatriz(matriz,5)}")

Matriz original 
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz desplazada 
[[4 5 6]
 [7 8 9]
 [1 2 3]]


16. Crear una matriz de 5x5 con números enteros aleatorios entre 0 y 20. Calcular y mostrar:
    - La suma de los elementos por cada fila.
    - La suma de los elementos por cada columna.

In [95]:
matriz = np.random.randint(0,20,size=[5,5])

print(matriz)
print()
print(f"SUMA FILA = {np.sum(matriz,axis=1)}")
print(f"SUMA COLUMNA = {np.sum(matriz,axis=0)}")

[[11 17 13 12  3]
 [ 0 14  3 12 18]
 [18  5 19  0  5]
 [ 0  1  1  4 16]
 [ 0 10  6  2 16]]

SUMA FILA = [56 47 47 22 34]
SUMA COLUMNA = [29 47 42 30 58]



17. Dada la matriz:

    matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [1, 2, 3],
                   [7, 8, 9]])

    - Eliminar las filas duplicadas.
    - Mostrar la matriz resultante sin filas duplicadas.

In [98]:
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [1, 2, 3],
                   [7, 8, 9]])

print(np.unique(matriz,axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]



18. Dada una matriz bidimensional de números enteros, crear una función que devuelva una nueva matriz donde cada elemento sea el producto de todos los elementos de la matriz original excepto el elemento actual, sin utilizar bucles. Mostrar la matriz original y la matriz resultante. Ejemplo de salida:
    
    Matriz original:
    [[1 2]
    [3 4]]

    Matriz resultante:
    [[24 12]
    [ 8  6]]

In [104]:
def calcularProductoSinN(matriz):
    mult = np.prod(matriz)
    print(mult)
    return mult / matriz 

matriz = np.arange(1,5).reshape(2,2)
print(f"Matriz original = {matriz}")
print(calcularProductoSinN(matriz))

Matriz original = [[1 2]
 [3 4]]
24
[[24. 12.]
 [ 8.  6.]]


19. Crear una matriz de 4x4 con números enteros aleatorios entre 1 y 10. Contar el número de elementos únicos en la matriz utilizando y mostrar el resultado.


In [107]:
matriz = np.random.randint(1,10,size=[4,4])
print(f"Cantidad de valores únicos: {np.unique(matriz).size}")

Cantidad de valores únicos: 7


20. Crear una matriz de 3x5 con números enteros aleatorios entre 0 y 50. Calcular y mostrar el valor acumulado de la suma de sus elementos a lo largo de cada fila. Ejemplo de salida:
    
    Matriz original:
    [[12  7 25 34 10]
    [ 3 47 20  5 41]
    [ 8 16 23  9 14]]

    Valor acumulado de la suma por filas:
    [[12 19 44 78 88]
    [ 3 50 70 75 116]
    [ 8 24 47 56 70]]





In [109]:
matriz = np.random.randint(50,size=[3,5])
print(matriz)
print(f"Valor acumulado por fila \n{np.cumsum(matriz,axis=1)}")

[[30  6 12 18 25]
 [35  2 24 28 10]
 [35 10 20  7  9]]
Valor acumulado por fila 
[[30 36 48 66 91]
 [35 37 61 89 99]
 [35 45 65 72 81]]


# Ejercicios Numpy con Imágenes

El siguiente código permite:
- Cargar una imagen y mostrarla.
- Pasarla a matriz de tipo numpy.
- Convertir una matriz de tipo numpy a imagen y mostrarla.

Y dada la imagen https://www.teleadhesivo.com/es/img/asfs212-png/folder/products-detalle-png/pegatinas-coches-motos-mario-bros-seta-pixel-rojo.png

Descarga la imagen y realiza las operaciones que se indican a continuación.

In [21]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

def image_to_numpy(image_path):
    """
    Abre una imagen desde la ruta especificada y la convierte en una matriz de NumPy.

    Args:
        image_path (str): Ruta al archivo de imagen.

    Returns:
        numpy.ndarray: Matriz de NumPy que representa la imagen.
    """
    # Abrir la imagen usando PIL
    image = Image.open(image_path)

    # Convertir la imagen a un array de NumPy
    image_array = np.array(image)

    return image_array

def mostrar_imagen(image_array):
    """
    Muestra una imagen a partir de una matriz de NumPy.

    Args:
        image_array (numpy.ndarray): Matriz de NumPy que representa la imagen.
    """
    plt.imshow(image_array)
    plt.axis('off')  # Ocultar los ejes
    plt.show()

def numpy_to_image(image_array, save_path=None):
    """
    Convierte una matriz de NumPy en una imagen y la muestra en pantalla.
    Opcionalmente, guarda la imagen en la ruta especificada.

    Args:
        image_array (numpy.ndarray): Matriz de NumPy que representa la imagen.
        save_path (str, optional): Ruta donde se guardará la imagen. Por defecto es None.
    
    Returns:
        PIL.Image.Image: Objeto de imagen de PIL.
    """
    # Convertir la matriz de NumPy a una imagen usando PIL
    image = Image.fromarray(image_array.astype('uint8'))

    # Mostrar la imagen usando matplotlib
    mostrar_imagen(image_array)

    # Guardar la imagen si se proporciona una ruta
    if save_path:
        image.save(save_path)
        print(f"Imagen guardada en: {save_path}")

    return image

# Ejemplo de uso
ruta_imagen = 'seta.png'  # Reemplaza con la ruta a tu imagen
imagen_numpy = image_to_numpy(ruta_imagen)

# Mostrar información de la matriz
print("Forma de la matriz:", imagen_numpy.shape)
print("Tipo de datos:", imagen_numpy.dtype)
print("Matriz de la imagen:\n", imagen_numpy)

# Mostrar la imagen
mostrar_imagen(imagen_numpy)

# Convertir la matriz de nuevo a una imagen y mostrarla
print("\nMostrando la imagen invertida utilizando numpy_to_image:")
imagen_invertida_pil = numpy_to_image(imagen_numpy)

# Opcional: Guardar la imagen
numpy_to_image(imagen_numpy, save_path='seta2.png')


ModuleNotFoundError: No module named 'PIL'

1. Rota la imagen hacia la derecha.
2. Cambia el color de la imagen a escala de grises.
3. Recorta la imagen para que solo se vea la parte de los ojos (el blanco y los ojos).
4. Cambia el color de los ojos a amarillo.
5. Crea una nueva imagen que contenga 4 setas, cada una con los ojos de cada color del parchís.
6. Dibúja una sonrisa a la seta.
7. Cambia el color de la seta a color verde.
8. Cambia el color de la seta a color azul y dibuja una boca que indique que es venenosa.