# Ejercicios Tensores

Indexación y slicing
======

1. Crea un tensor 1D con los números del 0 al 9 y extrae los elementos desde el índice 2 hasta el 5 (sin incluir el 5).


In [2]:
import torch
print(torch.arange(10)[2:5])

tensor([2, 3, 4])


2. Crea un tensor 2D de tamaño (3, 3) con los números del 1 al 9 y accede al elemento de la segunda fila y tercera columna.


In [3]:
tensor = torch.arange(1,10).reshape([3,3])
print(tensor[1][2])

tensor(6)


3. Crea un tensor 2D de tamaño (4, 4) con números aleatorios y extrae la primera columna de este tensor.


In [4]:
tensor = torch.randn(size=[4,4])
print(tensor)
print(tensor[:, 0])

tensor([[ 0.4997,  0.1513,  1.1936, -0.5089],
        [-1.3490,  0.6618, -0.3407,  1.5374],
        [ 1.1108,  1.3596,  1.3981,  0.0628],
        [-0.2285,  0.1307,  0.6505,  0.7383]])
tensor([ 0.4997, -1.3490,  1.1108, -0.2285])


4. Dado un tensor 3D de forma (2, 3, 4) con valores secuenciales del 0 al 23, extrae un subtensor que contenga todos los elementos de la segunda dimensión (índice 1) y las dos primeras columnas de la tercera dimensión.


In [5]:
tensor = torch.arange(24).reshape([2,3,4])
print(tensor)
print()
print(tensor[1, :])
print()
print(tensor[1, :,:2])

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

tensor([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])

tensor([[12, 13],
        [16, 17],
        [20, 21]])


5. Crea un tensor 2D de tamaño (5, 5) con números del 1 al 25 y reemplaza la submatriz central de tamaño (3, 3) por ceros.


In [6]:
tensor = torch.arange(1,26).reshape([5,5])
tensor[1:4,1:4] = 0
print(tensor)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  0,  0,  0, 10],
        [11,  0,  0,  0, 15],
        [16,  0,  0,  0, 20],
        [21, 22, 23, 24, 25]])


6. Dado un tensor 1D con 10 elementos aleatorios, invierte el orden de los elementos utilizando slicing.


In [7]:
tensor = torch.randn(10)
print(tensor)
print(torch.flip(tensor,[0]))

tensor([ 0.2592,  1.4011, -0.5148,  1.8600, -0.3232, -1.2067,  2.2073, -1.2059,
        -1.4073, -0.0575])
tensor([-0.0575, -1.4073, -1.2059,  2.2073, -1.2067, -0.3232,  1.8600, -0.5148,
         1.4011,  0.2592])


7. Crea un tensor 4D de forma (2, 3, 4, 5) con números aleatorios y extrae todos los elementos donde el índice de la primera dimensión es par y el índice de la tercera dimensión es impar.


In [8]:
tensor = torch.randint(10,100,[2,3,4,5])
print(tensor[::2,:,1::2,:])

tensor([[[[49, 57, 76, 15, 45],
          [68, 38, 56, 83, 52]],

         [[78, 93, 20, 37, 43],
          [58, 63, 53, 38, 51]],

         [[50, 12, 88, 70, 69],
          [21, 17, 51, 36, 11]]]])


8. Dado un tensor 2D de tamaño (6, 6) con valores del 1 al 36, extrae una submatriz de tamaño (3, 3) que esté en la esquina inferior derecha.


In [9]:
tensor = torch.arange(1,37).reshape([6,6])
print(tensor[-3:,-3:])

tensor([[22, 23, 24],
        [28, 29, 30],
        [34, 35, 36]])


9. Crea un tensor 3D de forma (3, 4, 5) con valores aleatorios y reemplaza todos los elementos que están en posiciones donde la suma de los índices es un número par por el valor -1.


In [10]:
tensor = torch.randn([3,4,5])
dim,j,k = torch.meshgrid(
    torch.arange(3),
    torch.arange(4),
    torch.arange(5)
)
mascara = (dim + j + k) % 2 == 0
tensor[mascara] = 0 
print(tensor)

tensor([[[ 0.0000,  0.1005,  0.0000, -0.7258,  0.0000],
         [ 0.4757,  0.0000, -0.6179,  0.0000,  0.7046],
         [ 0.0000,  1.0374,  0.0000, -0.9981,  0.0000],
         [ 0.4003,  0.0000,  0.4220,  0.0000,  0.3408]],

        [[ 0.7772,  0.0000,  1.1999,  0.0000,  0.3372],
         [ 0.0000,  0.3944,  0.0000,  0.6231,  0.0000],
         [ 0.4938,  0.0000, -0.6194,  0.0000, -1.0891],
         [ 0.0000, -0.0585,  0.0000, -0.1965,  0.0000]],

        [[ 0.0000, -0.3221,  0.0000, -1.7173,  0.0000],
         [-0.5115,  0.0000, -1.3286,  0.0000, -1.1357],
         [ 0.0000, -1.0158,  0.0000,  0.5550,  0.0000],
         [ 0.2137,  0.0000,  0.5396,  0.0000,  1.1171]]])


c:\Users\Marc\Desktop\pia\.venv\Lib\site-packages\torch\functional.py:505: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\aten\src\ATen\native\TensorShape.cpp:4383.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]


10. Dado un tensor 5D de forma (2, 2, 3, 3, 3) con valores secuenciales desde el 0 en adelante, extrae un subtensor que contenga todos los elementos cuya suma de los índices sea mayor que 5.


In [11]:
tensor = torch.arange(2*2*3*3*3).reshape(2,2,3,3,3)
#print(tensor)
indices = torch.meshgrid(
    torch.arange(2),
    torch.arange(2),
    torch.arange(3),
    torch.arange(3),
    torch.arange(3),
)
malla = sum(indices) > 5

print(tensor[malla])


tensor([ 26,  44,  50,  52,  53,  71,  77,  79,  80,  89,  95,  97,  98, 101,
        103, 104, 105, 106, 107])


Transformación de la Forma (Reshaping) de Tensores
================


1. Crea un tensor 1D con los números del 1 al 12 y transformarlo en un tensor 2D de forma (3, 4).


In [12]:
print(torch.arange(1,13).reshape(3,4))

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


2. Dado un tensor de forma (2, 6), cambiar su forma a (3, 4) utilizando una función de redimensionamiento.


In [13]:
tensor = torch.randn(size=[2,6])
print(tensor)
print(tensor.reshape(3,4))

tensor([[ 0.4184,  1.1628, -1.0453, -1.1288,  1.4263,  1.9400],
        [ 0.3407,  1.6112,  0.3225, -1.9665,  0.0999, -0.7079]])
tensor([[ 0.4184,  1.1628, -1.0453, -1.1288],
        [ 1.4263,  1.9400,  0.3407,  1.6112],
        [ 0.3225, -1.9665,  0.0999, -0.7079]])


3. Crear un tensor 2D de forma (4, 5) con números aleatorios y aplanarlo (flatten) en un tensor 1D.


In [14]:
tensor = torch.randn([4,5])
print(tensor.flatten())


tensor([ 0.7219,  0.7808,  0.0733,  0.6158,  0.4383,  0.2807, -0.6961, -0.0149,
        -0.6236,  1.2201, -0.2959, -1.0010,  0.8875, -0.0126,  0.5564,  1.5630,
         0.5975,  0.3626, -0.5916, -0.4170])


4. Dado un tensor 3D de forma (2, 3, 4) con valores secuenciales del 0 al 23, reordenar sus dimensiones para obtener un tensor de forma (3, 2, 4).


In [15]:
tensor = torch.arange(24).reshape(2,3,4)
print(tensor)
print(tensor.reshape(3,2,4))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]]])


5. Crear un tensor de forma (2, 2, 3) y transformarlo en un tensor de forma (6, 2) utilizando una operación de reshape.


In [16]:
tensor = torch.zeros(size=[2,2,3])
print(tensor) 
print(tensor.reshape(6,2)) 

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


6. Dado un tensor 1D de tamaño 16, cambiar su forma a un tensor 4D de forma (2, 2, 2, 2).


In [17]:
print(torch.arange(16).reshape(2,2,2,2))

tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]],

         [[12, 13],
          [14, 15]]]])


7. Crear un tensor 4D de forma (2, 3, 4, 5) con números aleatorios y aplanarlo en un tensor 2D donde la primera dimensión sea 2 y la segunda sea el producto de las dimensiones restantes.


In [18]:
tensor = torch.randn(size=[2,3,4,5])
multip = torch.prod(torch.tensor(tensor.shape[1:]))
print(tensor.reshape(2,multip))

tensor([[-1.1320,  0.3380, -0.3095, -0.8310, -0.7059,  1.0230, -1.0034, -0.1779,
          0.0864,  0.1056,  0.2002,  0.7345, -1.5144, -1.2169, -1.0184,  0.5142,
         -0.2149, -1.0871,  2.6738, -0.6112,  0.3047, -1.5406, -0.2566, -0.3711,
         -1.2208,  0.4425, -0.2243,  1.7743, -0.1794,  1.2514,  0.6238,  1.0153,
         -1.6195, -0.9132,  1.1443, -0.2564,  1.4016, -0.9353,  0.1407,  1.3248,
          0.6284,  0.4173,  2.2880,  0.3149,  0.7821,  1.3500,  1.0658,  0.2691,
         -0.8810,  0.7273, -1.5901, -0.1739,  3.0604, -0.7336,  0.2485, -0.9159,
         -0.6271, -0.2591,  1.3241,  2.1359],
        [-1.1738, -0.7761,  0.9871,  0.7429, -0.1785,  0.6835,  0.1528,  1.0129,
          1.3066,  1.2667, -0.1273, -0.2120,  0.3611,  0.2676,  1.4483, -0.9981,
         -0.4136,  0.2142, -1.2177, -0.1526, -1.2462, -1.3490, -1.1281,  0.4173,
         -0.2343, -0.2160, -0.4243, -0.1049,  1.3548, -0.8029, -1.1116, -2.7328,
          0.1057,  0.3580, -1.4903,  1.4005,  0.4145,  0.7929, 

8. Dado un tensor de forma (batch_size, height, width, channels) con dimensiones específicas, reordenar sus dimensiones para adaptarlo al formato (batch_size, channels, height, width), comúnmente utilizado en PyTorch.


In [19]:
batch_size, height, width, channels = 2,3,4,5

tensor = torch.randn(batch_size, height, width, channels)
print(tensor)
# Permute hay que pasarle los indice a cambiar enste caso 0 1 2 3 pasar a 0 3 1 2 channels pasaria al segundo lugar
print(tensor.permute(0,3,1,2))

tensor([[[[ 1.4768,  1.5398, -0.1388, -1.4063,  0.0193],
          [ 0.4142, -0.1388, -0.8396,  1.8921, -0.5999],
          [-0.3834, -0.5377, -0.2137, -0.2635,  0.4608],
          [-2.3001, -0.5043, -0.6524,  1.6423, -0.0650]],

         [[-0.3214,  0.3443,  0.0536, -0.9227,  1.3535],
          [-0.5707,  0.7831, -1.0023,  0.8623,  0.3036],
          [-2.4159, -1.3120,  0.5670, -0.2349,  0.5302],
          [-0.4233, -0.6842, -0.2962, -1.2258, -1.4896]],

         [[-1.1676, -1.0966, -0.2800, -0.0987, -0.4685],
          [ 0.9646,  0.4465, -0.8369,  0.4401, -0.0264],
          [ 1.8188,  1.4837, -0.4782, -1.0627, -0.1844],
          [ 0.4084, -0.8874,  1.0857,  0.2309, -1.6178]]],


        [[[-0.2066,  0.2538,  0.4275,  0.3274, -0.8157],
          [-0.7989, -0.2540,  0.4989, -0.4256,  1.0842],
          [-0.4234, -0.2570, -0.0533,  0.0993, -1.5044],
          [-0.1459, -0.7532, -0.8490,  0.7155,  0.0599]],

         [[ 1.5176, -1.2073,  0.7890, -1.3500,  0.3205],
          [-0.7624,  

9. Crear un tensor 2D de forma (6, 4) y dividirlo en tres tensores iguales a lo largo de la primera dimensión, luego concatenarlos de nuevo en una nueva dimensión para formar un tensor 3D.


In [20]:
tensor = torch.randn(size=[6,4])

chunks = tensor.chunk(chunks=3,dim=0)
    
for chunk in chunks:
    print(chunk)
    
print(torch.stack(chunks,dim=0))

tensor([[ 1.0066,  0.5445,  1.7775, -0.7768],
        [ 0.2269, -1.0894, -0.9151,  1.0334]])
tensor([[-0.0906,  0.8700, -0.0850,  0.9928],
        [ 1.4999, -0.3956,  0.0478,  0.2324]])
tensor([[ 1.4570,  0.0710, -0.8651, -0.1401],
        [-0.7893,  1.4874, -0.2865,  1.7277]])
tensor([[[ 1.0066,  0.5445,  1.7775, -0.7768],
         [ 0.2269, -1.0894, -0.9151,  1.0334]],

        [[-0.0906,  0.8700, -0.0850,  0.9928],
         [ 1.4999, -0.3956,  0.0478,  0.2324]],

        [[ 1.4570,  0.0710, -0.8651, -0.1401],
         [-0.7893,  1.4874, -0.2865,  1.7277]]])


10. Dado un tensor 5D de forma (2, 2, 3, 3, 3), transformar su forma para que las dos primeras dimensiones se combinen en una sola, obteniendo así un tensor de forma (4, 3, 3, 3).

In [21]:
tensor = torch.randn(size=[2,2,3,3,3])
suma = torch.sum(torch.tensor(tensor.shape[:2]))
print(tensor.reshape(suma,*tensor.shape[2:]))

tensor([[[[-0.2531,  1.8368,  0.6138],
          [-1.5708, -2.6927, -0.3745],
          [-0.9191, -0.1424, -1.8253]],

         [[ 0.8446,  0.8803, -0.2097],
          [ 0.8155,  0.7466, -1.4724],
          [ 0.4388, -0.7471,  0.3928]],

         [[-1.4903, -0.4015,  0.0826],
          [ 0.6260, -0.9127,  2.5618],
          [ 1.3466,  1.2293, -2.3460]]],


        [[[ 0.1422,  0.6243,  1.2123],
          [ 0.8719, -1.0577,  0.6974],
          [ 0.5072, -0.0455,  0.4461]],

         [[ 1.3962, -0.1942,  0.0529],
          [ 0.8936, -0.5975, -1.4058],
          [ 1.1148, -1.2146,  0.1762]],

         [[ 0.7350, -1.0625,  0.1135],
          [-0.7563, -0.2087,  3.0766],
          [-1.0793,  1.6869, -0.0462]]],


        [[[ 0.8777,  1.1743,  0.6281],
          [-0.2014,  0.4639, -0.1127],
          [ 0.2804,  0.5496,  0.5723]],

         [[-0.6306,  0.0774,  0.4710],
          [ 1.2463, -0.3176,  1.6067],
          [-1.6206, -0.5228,  0.8951]],

         [[ 0.3992,  0.6118,  1.5458],
     

Operaciones Matemáticas Básicas con Tensores
================
1. Crear dos tensores 1D de tamaño 5 con números aleatorios y calcular su suma elemento a elemento.

In [22]:
tensor1 = torch.randn(5)
tensor2 = torch.randn(5)

print(tensor1)
print(tensor2)
print(tensor1 + tensor2)

tensor([-0.3507, -0.1778, -1.5239,  0.0932, -0.5514])
tensor([-0.3300,  0.9346,  0.1797, -0.6295, -1.4087])
tensor([-0.6807,  0.7568, -1.3442, -0.5363, -1.9601])


2. Dado un tensor 2D de tamaño (3, 3) con valores del 1 al 9, calcular el promedio de todos sus elementos.


In [23]:
tensor = torch.arange(1,10).reshape(3,3)
print(torch.prod(tensor))

tensor(362880)


3. Crear un tensor 2D de tamaño (4, 4) con valores aleatorios y multiplicarlo por un escalar de valor 2.


In [24]:
print(torch.randn(4,4)*2)

tensor([[ 0.0409,  1.4134, -1.0029, -2.4623],
        [ 0.6790, -0.4352, -1.4441, -3.6231],
        [ 1.1796, -0.5049,  1.0458,  3.7664],
        [-1.7063, -3.7406, -1.1046, -0.0942]])


4. Dado un tensor 2D de forma (2, 3) y otro tensor 2D de forma (3, 2), realizar una multiplicación matricial entre ambos y mostrar el resultado.


In [25]:
tensor1 = torch.arange(2*3).reshape(2,3)
tensor2 = torch.arange(3*2).reshape(3,2)
print(tensor1)
print()
print(tensor2)
print()
print(tensor1 @ tensor2)

tensor([[0, 1, 2],
        [3, 4, 5]])

tensor([[0, 1],
        [2, 3],
        [4, 5]])

tensor([[10, 13],
        [28, 40]])


5. Crear un tensor 3D de forma (2, 3, 4) con valores aleatorios y calcular la suma de los elementos a lo largo de la segunda dimensión (dim=1 o axis=1).


In [26]:
tensor = torch.randint(10,20,size=[2,3,4])
print(tensor)

print(torch.sum(tensor,dim=1))


tensor([[[17, 17, 10, 10],
         [19, 12, 18, 18],
         [14, 12, 17, 14]],

        [[19, 11, 14, 16],
         [13, 13, 11, 17],
         [12, 11, 14, 12]]])
tensor([[50, 41, 45, 42],
        [44, 35, 39, 45]])


6. Dado un tensor 2D de tamaño (5, 5) con valores del 1 al 25, calcular el producto elemento a elemento con su transpuesta.


In [27]:
tensor = torch.arange(1,26).reshape(5,5)
print(tensor)
print(tensor.T)
print(tensor*tensor.T)

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25]])
tensor([[ 1,  6, 11, 16, 21],
        [ 2,  7, 12, 17, 22],
        [ 3,  8, 13, 18, 23],
        [ 4,  9, 14, 19, 24],
        [ 5, 10, 15, 20, 25]])
tensor([[  1,  12,  33,  64, 105],
        [ 12,  49,  96, 153, 220],
        [ 33,  96, 169, 252, 345],
        [ 64, 153, 252, 361, 480],
        [105, 220, 345, 480, 625]])


7. Crear dos tensores 3D de forma (2, 3, 4) y (2, 4, 3) con valores aleatorios y realizar una multiplicación matricial por lotes (batch matrix multiplication).


In [28]:
tensor1 = torch.randint(10,20,size=[2,3,4])
tensor2 = torch.randint(10,20,size=[2,4,3])
#torch.bmm hace tensor1[x] @ tensor1[x] internamente para obtner la matricial de cada lote
result = torch.bmm(tensor1,tensor2)
print(result)

tensor([[[ 749,  889,  913],
         [ 689,  846,  834],
         [ 807, 1024,  984]],

        [[ 822,  751,  743],
         [ 915,  827,  779],
         [ 781,  695,  679]]])


8. Dado un tensor 4D de forma (2, 3, 4, 5), calcular el promedio de los elementos a lo largo de las dimensiones 2 y 3.


In [29]:
tensor = torch.randint(10,20,size=[2,3,4,5]).to(torch.float64)

print(torch.mean(tensor,dim=(2,3)))

tensor([[15.8000, 14.9500, 14.5000],
        [15.1000, 14.9000, 14.9000]], dtype=torch.float64)


9. Crear un tensor 2D de forma (3, 3) con valores del 1 al 9 y calcular el determinante de este tensor (nota: puede requerir convertir el tensor a tipo float).


In [30]:
tensor = torch.arange(1,10).reshape(3,3).to(torch.float64)
print(torch.det(tensor))

tensor(0., dtype=torch.float64)


10. Dado un tensor 3D de forma (3, 3, 3) con valores aleatorios, normalizar el tensor restando la media y dividiendo por la desviación estándar de todos los elementos.

In [31]:
tensor = torch.randint(10,size=[3,3,3]).to(torch.float64)
media = torch.mean(tensor)
desviacionStandar = torch.std(tensor)
print(tensor)
print(media)
print(desviacionStandar)
print(f"Normalizado: \n{(tensor - media) / desviacionStandar}")

tensor([[[3., 5., 9.],
         [4., 7., 0.],
         [2., 8., 5.]],

        [[0., 8., 0.],
         [8., 4., 3.],
         [3., 0., 4.]],

        [[4., 0., 5.],
         [6., 4., 6.],
         [0., 6., 7.]]], dtype=torch.float64)
tensor(4.1111, dtype=torch.float64)
tensor(2.8330, dtype=torch.float64)
Normalizado: 
tensor([[[-0.3922,  0.3138,  1.7257],
         [-0.0392,  1.0197, -1.4512],
         [-0.7452,  1.3727,  0.3138]],

        [[-1.4512,  1.3727, -1.4512],
         [ 1.3727, -0.0392, -0.3922],
         [-0.3922, -1.4512, -0.0392]],

        [[-0.0392, -1.4512,  0.3138],
         [ 0.6668, -0.0392,  0.6668],
         [-1.4512,  0.6668,  1.0197]]], dtype=torch.float64)


Concatenación y Apilamiento
=====================================
1. Crear dos tensores 1D de tamaño 5 con números del 1 al 5 y del 6 al 10, y concatenarlos para formar un tensor de tamaño 10.

In [32]:
tensor1 = torch.arange(1,6)
tensor2 = torch.arange(6,11)
print(torch.concatenate((tensor1,tensor2)))

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])


2. Dado tres tensores 2D de forma (2, 2) con valores aleatorios, apilarlos a lo largo de una nueva dimensión para formar un tensor 3D.


In [33]:
tensores = [torch.randint(10,size=[2,2]) for _ in range(3)]
print(torch.stack(tensores))

tensor([[[3, 0],
         [8, 2]],

        [[0, 0],
         [2, 5]],

        [[5, 0],
         [5, 1]]])


3. Crear dos tensores 2D de forma (3, 4) y concatenarlos a lo largo de la dimensión de las columnas para obtener un tensor de forma (3, 8).


In [34]:
tensores = [torch.randint(10,size=[3,4]) for _ in range(2)]
print(torch.concatenate(tensores,dim=1))

tensor([[5, 3, 5, 7, 6, 1, 1, 1],
        [2, 3, 2, 7, 9, 4, 9, 1],
        [5, 3, 5, 7, 0, 5, 2, 4]])


4. Dado cuatro tensores 2D de forma (2, 3), concatenarlos y apilarlos de todas las formas posibles y mostrar las formas resultantes de los tensores obtenidos.


In [35]:
tensores = [torch.randint(10,size=[2,3]) for _ in range(4)]

print("********* DIM 0 *********")
print(torch.concatenate(tensores,dim=0))
print(torch.stack(tensores,dim=0))
print("********* DIM 1 *********")
print(torch.concatenate(tensores,dim=1))
print(torch.stack(tensores,dim=1))


********* DIM 0 *********
tensor([[1, 6, 6],
        [6, 9, 3],
        [9, 8, 0],
        [8, 4, 1],
        [0, 2, 2],
        [1, 8, 4],
        [1, 6, 6],
        [3, 0, 7]])
tensor([[[1, 6, 6],
         [6, 9, 3]],

        [[9, 8, 0],
         [8, 4, 1]],

        [[0, 2, 2],
         [1, 8, 4]],

        [[1, 6, 6],
         [3, 0, 7]]])
********* DIM 1 *********
tensor([[1, 6, 6, 9, 8, 0, 0, 2, 2, 1, 6, 6],
        [6, 9, 3, 8, 4, 1, 1, 8, 4, 3, 0, 7]])
tensor([[[1, 6, 6],
         [9, 8, 0],
         [0, 2, 2],
         [1, 6, 6]],

        [[6, 9, 3],
         [8, 4, 1],
         [1, 8, 4],
         [3, 0, 7]]])


5. Crear una lista de 5 tensores 1D de tamaño 4 con valores aleatorios y apilarlos a lo largo de una nueva dimensión para formar un tensor 2D.


In [36]:
tensores = [torch.randint(10,size=[4]) for _ in range(5)]
print(torch.stack(tensores))

tensor([[5, 8, 6, 7],
        [5, 2, 4, 1],
        [0, 2, 3, 4],
        [0, 5, 3, 6],
        [6, 8, 2, 7]])


6. Dado un tensor 3D de forma (2, 3, 4), dividirlo en dos tensores a lo largo de la dimensión 1 y luego concatenarlos a lo largo de la dimensión 2.


In [37]:
tensor = torch.randint(10,size=[2,3,4])

print(tensor)
print()
lista = torch.split(tensor,split_size_or_sections=1, dim=0)

for t in lista:
    print(t)
    print()
print(torch.concatenate(lista,dim=2))

tensor([[[7, 0, 0, 7],
         [4, 8, 6, 4],
         [6, 5, 0, 6]],

        [[7, 2, 0, 8],
         [9, 9, 9, 6],
         [5, 4, 9, 5]]])

tensor([[[7, 0, 0, 7],
         [4, 8, 6, 4],
         [6, 5, 0, 6]]])

tensor([[[7, 2, 0, 8],
         [9, 9, 9, 6],
         [5, 4, 9, 5]]])

tensor([[[7, 0, 0, 7, 7, 2, 0, 8],
         [4, 8, 6, 4, 9, 9, 9, 6],
         [6, 5, 0, 6, 5, 4, 9, 5]]])


7. Crear tres tensores 4D de forma (2, 2, 3, 3) con valores aleatorios y apilarlos para formar un tensor 5D, luego reorganizar sus dimensiones para obtener un tensor de forma (2, 3, 2, 3, 3).


In [38]:
tensores = [torch.randint(10,size=[2,2,3,3]) for _ in range(3)]
newT = torch.stack(tensores,dim=4).permute(0,2,1,3,4)
print(newT)
print(newT.shape)

tensor([[[[[4, 2, 7],
           [4, 7, 0],
           [4, 6, 6]],

          [[5, 9, 3],
           [8, 0, 2],
           [2, 6, 8]]],


         [[[0, 0, 1],
           [5, 2, 0],
           [0, 5, 0]],

          [[4, 9, 8],
           [5, 5, 7],
           [0, 3, 2]]],


         [[[4, 6, 1],
           [6, 8, 7],
           [2, 2, 7]],

          [[7, 1, 6],
           [8, 4, 3],
           [7, 4, 2]]]],



        [[[[4, 1, 9],
           [6, 8, 4],
           [3, 3, 2]],

          [[1, 7, 7],
           [7, 7, 3],
           [9, 1, 0]]],


         [[[9, 5, 9],
           [8, 6, 2],
           [1, 2, 0]],

          [[6, 3, 6],
           [1, 7, 8],
           [5, 2, 6]]],


         [[[1, 6, 9],
           [9, 1, 3],
           [0, 1, 8]],

          [[7, 4, 6],
           [0, 6, 4],
           [5, 7, 4]]]]])
torch.Size([2, 3, 2, 3, 3])


8. Dado un tensor 2D de forma (6, 4), dividirlo en tres tensores iguales a lo largo de la primera dimensión y luego concatenarlos a lo largo de una nueva dimensión para formar un tensor 3D de forma (3, 2, 4).


In [39]:
tensor = torch.randint(10,size=[6,4])
tensores = torch.split(tensor,2,dim=0)
stack = torch.stack(tensores,dim=1).permute(1,0,2)
print(stack)
print(stack.shape)

tensor([[[0, 5, 7, 1],
         [0, 1, 1, 7]],

        [[2, 7, 6, 1],
         [4, 6, 4, 6]],

        [[4, 1, 8, 6],
         [7, 1, 4, 6]]])
torch.Size([3, 2, 4])


9. Crear dos tensores 3D de formas incompatibles para concatenación directa (por ejemplo, formas (2, 3, 4) y (3, 2, 4)), aplicar las transformaciones necesarias para poder concatenarlos a lo largo de una dimensión específica.


In [40]:
tensor1 = torch.randint(10,size=[2,3,4])
tensor2 = torch.randint(10,size=[3,2,4]).permute(1,0,2)

print(torch.concatenate((tensor1,tensor2),dim=1))


tensor([[[5, 6, 5, 3],
         [7, 4, 2, 1],
         [6, 6, 1, 9],
         [7, 4, 1, 7],
         [4, 5, 1, 4],
         [5, 2, 6, 1]],

        [[3, 7, 6, 5],
         [4, 6, 7, 0],
         [6, 4, 3, 5],
         [0, 5, 3, 8],
         [2, 1, 0, 1],
         [0, 2, 0, 9]]])



10. Dado un tensor 4D de forma (2, 3, 4, 5), dividirlo en dos tensores a lo largo de la segunda dimensión y luego apilar uno sobre el otro para formar un tensor de forma (4, 3, 4, 5).


In [41]:
tensor = torch.randint(10,size=[2,4,4,5])
t1,t2 = torch.split(tensor,2,1)

print(torch.cat((t1,t2),dim=0).size())

torch.Size([4, 2, 4, 5])


Broadcasting
=======
1. Crear un tensor 1D con valores del 1 al 5 y sumar un escalar de valor 10 utilizando broadcasting.


In [42]:
tensor = torch.arange(1,6)
print(tensor + 10)

tensor([11, 12, 13, 14, 15])


2. Dado un tensor 2D de forma (3, 4) con valores aleatorios, sumar un tensor 1D de tamaño 4 a cada fila utilizando broadcasting.


In [43]:
tensor = torch.randint(10,size=[3,4])
tensorSumar = torch.tensor([1,2,3,4])
print(tensor)
print(tensor + tensorSumar)

tensor([[4, 7, 6, 8],
        [9, 2, 4, 1],
        [4, 6, 1, 2]])
tensor([[ 5,  9,  9, 12],
        [10,  4,  7,  5],
        [ 5,  8,  4,  6]])


3. Multiplicar un tensor 2D de forma (4, 1) por un tensor 1D de tamaño 3 utilizando broadcasting para obtener un tensor de forma (4, 3).


In [44]:
tensor1 = torch.randint(10,size=[4,1])
tensor2 = torch.tensor([1,2,3])
print(tensor1)
print(tensor1 * tensor2)

tensor([[6],
        [9],
        [1],
        [1]])
tensor([[ 6, 12, 18],
        [ 9, 18, 27],
        [ 1,  2,  3],
        [ 1,  2,  3]])


4. Crear dos tensores, uno de forma (2, 3, 4) y otro de forma (4,), y realizar una suma utilizando broadcasting.


In [45]:
tensor1 = torch.randint(10,size=[2,3,4])
tensor2 = torch.tensor([1,2,3,4])
print(tensor1 + tensor2)

tensor([[[ 9,  3,  4,  5],
         [ 9,  5,  8,  4],
         [ 6,  8,  5, 11]],

        [[ 2,  4,  3, 11],
         [ 3, 10, 10, 11],
         [ 6,  2,  3,  8]]])


5. Dado un tensor 3D de forma (5, 1, 6) y un tensor 2D de forma (5, 6), realizar una multiplicación elemento a elemento utilizando broadcasting.


In [46]:
tensor1 = torch.randint(10,size=[5,1,6])
tensor2 = torch.randint(10,size=[5,6])
print(tensor1 * tensor2)


tensor([[[10,  0, 35, 72, 35, 14],
         [ 5,  0, 42, 24, 30,  8],
         [ 5,  0, 42,  8,  0, 18],
         [15,  0,  0, 64,  0,  4],
         [ 0,  0, 56, 72,  0, 18]],

        [[ 4, 45,  0, 45,  0, 56],
         [ 2, 81,  0, 15,  0, 32],
         [ 2, 72,  0,  5,  0, 72],
         [ 6, 81,  0, 40,  0, 16],
         [ 0,  9,  0, 45,  0, 72]],

        [[ 4, 25, 40, 45, 42, 56],
         [ 2, 45, 48, 15, 36, 32],
         [ 2, 40, 48,  5,  0, 72],
         [ 6, 45,  0, 40,  0, 16],
         [ 0,  5, 64, 45,  0, 72]],

        [[14, 25, 15, 27,  7, 63],
         [ 7, 45, 18,  9,  6, 36],
         [ 7, 40, 18,  3,  0, 81],
         [21, 45,  0, 24,  0, 18],
         [ 0,  5, 24, 27,  0, 81]],

        [[14,  0, 40, 63, 21, 35],
         [ 7,  0, 48, 21, 18, 20],
         [ 7,  0, 48,  7,  0, 45],
         [21,  0,  0, 56,  0, 10],
         [ 0,  0, 64, 63,  0, 45]]])


6. Crear dos tensores, uno de forma (1, 3, 4) y otro de forma (2, 1, 4), y sumarlos utilizando broadcasting para obtener un tensor de forma (2, 3, 4).


In [47]:
tensor1 = torch.randint(10,size=[1,3,4])
tensor2 = torch.randint(10,size=[2,1,4])
print((tensor1+tensor2))
print((tensor1+tensor2).size())

tensor([[[ 8,  9, 16,  7],
         [10,  9,  9,  6],
         [ 3,  1,  8, 13]],

        [[10, 11, 17,  6],
         [12, 11, 10,  5],
         [ 5,  3,  9, 12]]])
torch.Size([2, 3, 4])


7. Dado un tensor 4D de forma (2, 1, 3, 1) y otro tensor 3D de forma (1, 4, 1), realizar una multiplicación utilizando broadcasting para obtener un tensor de forma (2, 4, 3, 1).


In [48]:
tensor1 = torch.randint(10,size=[2,1,3,1])
tensor2 = torch.randint(10,size=[1,4,1])
tensor2 = tensor2.unsqueeze(dim=-1)
print(tensor1 * tensor2)
print((tensor1 * tensor2).shape)

tensor([[[[ 6],
          [ 0],
          [ 6]],

         [[24],
          [ 0],
          [24]],

         [[24],
          [ 0],
          [24]],

         [[18],
          [ 0],
          [18]]],


        [[[14],
          [ 2],
          [16]],

         [[56],
          [ 8],
          [64]],

         [[56],
          [ 8],
          [64]],

         [[42],
          [ 6],
          [48]]]])
torch.Size([2, 4, 3, 1])


8. Crear tres tensores de formas (3, 1, 1), (1, 4, 1) y (1, 1, 5). Sumar los tres tensores utilizando broadcasting para obtener un tensor de forma (3, 4, 5).


In [49]:
tensor1 = torch.randint(10,size=[3,1,1])
tensor2 = torch.randint(10,size=[1,4,1])
tensor3 = torch.randint(10,size=[1,1,5])

print(tensor1+tensor2+tensor3)

tensor([[[15, 17, 17, 12, 16],
         [15, 17, 17, 12, 16],
         [18, 20, 20, 15, 19],
         [19, 21, 21, 16, 20]],

        [[11, 13, 13,  8, 12],
         [11, 13, 13,  8, 12],
         [14, 16, 16, 11, 15],
         [15, 17, 17, 12, 16]],

        [[ 8, 10, 10,  5,  9],
         [ 8, 10, 10,  5,  9],
         [11, 13, 13,  8, 12],
         [12, 14, 14,  9, 13]]])


9. Dado un tensor 2D de forma (m, n), donde m y n son variables, crear una función que sume un vector de tamaño n a cada fila del tensor utilizando broadcasting, y probarla con diferentes valores de m y n.


In [50]:
def sumarVector(m,n):
    t = torch.randint(10,size=[m,n])
    t2 = torch.arange(n)
    print(t+t2)

sumarVector(5,6)
sumarVector(2,1)
sumarVector(3,9)
sumarVector(8,8)

tensor([[ 8,  3,  6, 11,  6, 13],
        [ 6,  3,  8,  6, 13, 11],
        [ 3,  4,  2,  3,  6, 12],
        [ 7,  6,  9, 12,  4,  5],
        [ 9,  8,  9,  8, 10, 12]])
tensor([[4],
        [1]])
tensor([[ 6,  8,  4,  6,  4, 13,  7, 16,  8],
        [ 4, 10, 11,  9,  4,  6,  8, 11, 17],
        [ 0,  3,  8,  3,  7, 14,  7,  9, 10]])
tensor([[ 8,  4,  4,  4,  6, 14, 14, 10],
        [ 4,  7, 11,  5,  9, 13, 10, 16],
        [ 6,  7,  7,  4, 13,  9,  7,  9],
        [ 2,  5,  2, 11,  6, 13,  7, 15],
        [ 1,  2,  8,  4,  4,  8,  8,  9],
        [ 1,  8,  9,  4,  7, 13, 14, 13],
        [ 8,  6, 10,  4, 10,  8,  6, 13],
        [ 5,  9,  4,  3,  6, 13, 10, 15]])


10. Explicar por qué la operación de suma entre un tensor de forma (2, 3, 4) y otro de forma (3, 4) es válida utilizando broadcasting, y demostrarlo con código.

In [51]:
'''
Al hacer operaciones de broadcasting se lee el tamaño de las dimensiones de derecha a izquireda lo que hace es leer 4 con el 4 el 3 con 3, la primera dimension al estar vacia se interpreta como 1 lo cual tambien es valido, para que de error seria por ejemplo [2,3,4] y [3,5]
'''


t1 = torch.randint(10,size=[2,3,4])
t2 = torch.randint(10,size=[3,4])
print("T1")
print(t1)
print("T2")
print(t2)
print("Result")
print(t1 + t2)

T1
tensor([[[9, 8, 8, 5],
         [8, 7, 3, 9],
         [0, 7, 0, 1]],

        [[8, 0, 6, 9],
         [1, 1, 7, 7],
         [1, 0, 2, 3]]])
T2
tensor([[3, 3, 2, 8],
        [0, 0, 2, 9],
        [7, 4, 9, 3]])
Result
tensor([[[12, 11, 10, 13],
         [ 8,  7,  5, 18],
         [ 7, 11,  9,  4]],

        [[11,  3,  8, 17],
         [ 1,  1,  9, 16],
         [ 8,  4, 11,  6]]])


Squeezing y Unsqueezing
=======
1. Crear un tensor 1D de tamaño 5 y agregar una nueva dimensión en la posición 0 para convertirlo en un tensor 2D de forma (1, 5) utilizando unsqueeze o expand_dims.

In [52]:
tensor = torch.arange(5)
print(tensor)
print(tensor.unsqueeze(dim=0))

tensor([0, 1, 2, 3, 4])
tensor([[0, 1, 2, 3, 4]])


2. Dado un tensor de forma (1, 3, 1, 5), eliminar las dimensiones de tamaño 1 para obtener un tensor de forma (3, 5) utilizando squeeze.


In [53]:
tensor = torch.randint(10,size=[1,3,1,5])
print(tensor)
print(tensor.squeeze())

tensor([[[[9, 3, 1, 8, 9]],

         [[1, 0, 5, 8, 6]],

         [[6, 7, 6, 5, 0]]]])
tensor([[9, 3, 1, 8, 9],
        [1, 0, 5, 8, 6],
        [6, 7, 6, 5, 0]])


3. Crear un tensor 2D de forma (4, 4) y agregar una nueva dimensión al final para obtener un tensor de forma (4, 4, 1).


In [54]:
tensor = torch.randint(10,size=[4,4])
print(tensor.unsqueeze(-1))
print(tensor.unsqueeze(-1).size())

tensor([[[5],
         [4],
         [2],
         [5]],

        [[3],
         [2],
         [3],
         [9]],

        [[7],
         [5],
         [4],
         [9]],

        [[0],
         [8],
         [7],
         [5]]])
torch.Size([4, 4, 1])


4. Dado un tensor de forma (2, 1, 3, 1, 4), eliminar todas las dimensiones de tamaño 1 excepto la primera utilizando squeeze con el parámetro dim o axis.


In [55]:
tensor = torch.randint(10,size=[2,1,3,1,4])
dimDelete = []
for i,dim in enumerate(tensor.size()):
    if dim == 1:
        dimDelete.append(i)
dimDelete = dimDelete[1:]
print(tensor.squeeze(dim=dimDelete).shape)

torch.Size([2, 1, 3, 4])


5. Crear un tensor 1D de tamaño 10 y transformarlo en un tensor 4D de forma (1, 10, 1, 1) utilizando unsqueeze o expand_dims varias veces.


In [56]:
tensor = torch.arange(10)
tensor = tensor.unsqueeze(0)
tensor = tensor.unsqueeze(-1)
tensor = tensor.unsqueeze(-1)
print(tensor.shape)


torch.Size([1, 10, 1, 1])


6. Dado un tensor 3D de forma (batch_size, height, width), agregar una dimensión de canales para convertirlo en un tensor de forma (batch_size, height, width, channels=1).


In [57]:
batch_size, height, width = 5,6,2
channels = 1
tensor = torch.randint(10,[batch_size, height, width])
print(tensor.shape)
print(tensor.unsqueeze(-1).shape)

torch.Size([5, 6, 2])
torch.Size([5, 6, 2, 1])


7. Crear una función que reciba un tensor de cualquier forma y devuelva un tensor sin dimensiones de tamaño 1 (aplicando squeeze), y luego agregar una dimensión de tamaño 1 al inicio y al final del tensor resultante.


In [58]:
def dimPurge(t):
    t = t.squeeze()
    t = t.unsqueeze(0)
    t = t.unsqueeze(-1)
    return t
    
t = torch.randn([1,5,9,8,4,6,2,5,1,6,4,5])
print(dimPurge(t).shape)

torch.Size([1, 5, 9, 8, 4, 6, 2, 5, 6, 4, 5, 1])


8. Dado un tensor 4D de forma (batch_size, channels, height, width), reordenar sus dimensiones para convertirlo al formato (batch_size, height, width, channels), y luego eliminar cualquier dimensión de tamaño 1.


In [59]:
batch_size,channels ,height, width = 5,1,6,2

tensor = torch.randint(10,[batch_size,channels, height, width])
tensor = tensor.permute(0,2,3,1)
tensor = tensor.squeeze()
print(tensor.shape)

torch.Size([5, 6, 2])


9. Explicar y demostrar con código cómo el uso incorrecto de squeeze y unsqueeze puede llevar a errores en las operaciones de concatenación de tensores, y cómo solucionarlo.


In [60]:
'''
        Al squezze en momentos que no tocan antes de concatenar puedes alterar la forma del tensor haciendo que de error al intentar concatenar 2 tensores con diferente forma, la solucion seria ajustar el tensor con unsquezze volviendo a poner la dimension borrada    
'''

t1 = torch.randn([3,1,4])
t2 = torch.randn([3,1,4])
print(torch.concatenate((t1,t2)).shape)
t2 = t2.squeeze()
try:
    print(torch.concatenate((t1,t2)).shape)
except:
    print("Error arreglando tensor")
    t2 = t2.unsqueeze(1)
    print(torch.concatenate((t1,t2)).shape)

torch.Size([6, 1, 4])
Error arreglando tensor
torch.Size([6, 1, 4])



10. Dado un tensor 5D de forma (1, 2, 1, 3, 1), eliminar selectivamente las dimensiones de tamaño 1 utilizando squeeze con el parámetro dim o axis, para obtener un tensor de forma (2, 1, 3).

In [61]:
tensor = torch.randint(10,size=[1,2,1,3,1])
print(tensor.shape)
print(tensor.squeeze(dim=(0,-1)).shape)

torch.Size([1, 2, 1, 3, 1])
torch.Size([2, 1, 3])


División y División Matricial
========
1. Crear un tensor 1D con los números del 0 al 9 y dividirlo en tres tensores de tamaños iguales utilizando una operación de división.


In [62]:
tensor = torch.arange(9)
split = torch.split(tensor,(tensor.size()[0] // 3))
for i in split:
    print(i)
    print

tensor([0, 1, 2])
tensor([3, 4, 5])
tensor([6, 7, 8])


2. Dado un tensor 2D de forma (4, 4) con valores del 1 al 16, dividirlo en dos tensores a lo largo de la dimensión de las filas (dimensión 0), obteniendo dos tensores de forma (2, 4).


In [63]:
tensor = torch.arange(1,17).reshape(4,4)
split = torch.split(tensor, tensor.size()[0]//2)
print(split)

(tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]]), tensor([[ 9, 10, 11, 12],
        [13, 14, 15, 16]]))


3. Crear un tensor 2D de forma (6, 3) y dividirlo en tres tensores a lo largo de la dimensión de las filas, cada uno de forma (2, 3).


In [64]:
tensor = torch.randint(10,size=[6,3])
split = torch.split(tensor, tensor.size()[0]//3)
for i in split:
    print(i.shape)


torch.Size([2, 3])
torch.Size([2, 3])
torch.Size([2, 3])


4. Dado un tensor 3D de forma (4, 6, 2), dividirlo en dos tensores a lo largo de la segunda dimensión (dimensión 1), obteniendo tensores de forma (4, 3, 2).


In [65]:
tensor = torch.randint(10,size=[4,6,2])
split = torch.split(tensor, tensor.size()[1]//2,dim=1)
for i in split:
    print(i.shape)


torch.Size([4, 3, 2])
torch.Size([4, 3, 2])


5. Crear un tensor 1D de tamaño 10 y dividirlo en tensores de tamaños [3, 3, 4] utilizando una operación de división con tamaños específicos.


In [66]:
tensor = torch.randint(10,size=[10])
split = torch.split(tensor, [3,3,4])
for i in split:
    print(i.shape)


torch.Size([3])
torch.Size([3])
torch.Size([4])


6. Dado un tensor 2D de forma (8, 4), dividirlo en cuatro tensores iguales a lo largo de la primera dimensión y luego concatenarlos a lo largo de la segunda dimensión para formar un tensor de forma (2, 16).


In [67]:
tensor = torch.randint(10,size=[8,4])
split = torch.split(tensor, tensor.size()[0]//4,dim=0)
for i in split:
    print(i.shape)
print(torch.concatenate(split,dim=1).shape)

torch.Size([2, 4])
torch.Size([2, 4])
torch.Size([2, 4])
torch.Size([2, 4])
torch.Size([2, 16])


7. Crear un tensor 4D de forma (2, 8, 4, 4) y dividirlo en dos tensores a lo largo de la segunda dimensión, luego realizar una operación de multiplicación matricial entre ellos.


In [68]:
tensor = torch.randint(10,size=[2,8,4,4])
split = torch.split(tensor, tensor.size()[2]//2,dim=2)
for i in split:
    print(i.shape)
print(split[0] @ split[1].transpose(-1,-2))

torch.Size([2, 8, 2, 4])
torch.Size([2, 8, 2, 4])
tensor([[[[ 52,  57],
          [ 91,  60]],

         [[ 50,  51],
          [ 45,  56]],

         [[ 43,  93],
          [ 62, 121]],

         [[119,  77],
          [129,  77]],

         [[ 33,  40],
          [106,  80]],

         [[ 59,  54],
          [ 60,  82]],

         [[ 44,  62],
          [ 82, 113]],

         [[ 56, 117],
          [ 93, 153]]],


        [[[ 55, 104],
          [ 56,  33]],

         [[ 85,  91],
          [ 66,  58]],

         [[ 93,  58],
          [118,  85]],

         [[ 36,  36],
          [116,  91]],

         [[151, 137],
          [ 86,  59]],

         [[ 64,  95],
          [ 92, 122]],

         [[ 41,  66],
          [ 55,  84]],

         [[ 25,  69],
          [ 70, 103]]]])


8. Dado un tensor 3D de forma (3, 6, 9), escribir una función que lo divida en tensores más pequeños de forma (3, 2, 3) a lo largo de las dimensiones 1 y 2, y luego procese cada uno de los pequeños tensores individualmente.


In [69]:
def procesarTensores(tensor):
    
    split = torch.split(tensor, tensor.size()[1]//3,dim=1)
    split2 = [torch.split(tensor, tensor.size()[2]//3,dim=2) for tensor in split] 
    for tupla in split2:
        for i in tupla:
            print(i.shape)
    
tensor = torch.randint(10,size=[3,6,9])
procesarTensores(tensor)

torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 2, 3])
torch.Size([3, 2, 3])


9. Crear un tensor 2D de forma (7, 7) y dividirlo en cuatro submatrices cuadradas (o lo más cercano posible) utilizando operaciones de slicing y sin utilizar funciones de división predefinidas.


In [70]:
tensor = torch.randint(10,size=[7,7])
t1 = tensor[:4, :4]
t2 = tensor[:4, 4:]
t3 = tensor[4:, 4:]
t4 = tensor[4:, :4]

print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([4, 4])
torch.Size([4, 3])
torch.Size([3, 3])
torch.Size([3, 4])


10. Dado un tensor 5D de forma (2, 4, 6, 8, 10), dividirlo en tensores más pequeños de tal manera que cada tensor tenga forma (2, 4, 3, 4, 5), y luego realizar una operación personalizada en cada uno de los tensores resultantes.

In [73]:
tensor = torch.randint(10,size=[2,4,6,8,10])

tensores = []

# dividir dim 2
for t in torch.split(tensor, tensor.size(2)//2, dim=2):
    tensores.append(t)

# dividir dim 3
temp = []
for t in tensores:
    temp.extend(torch.split(t, t.size(3)//2, dim=3))

tensores = temp

# dividir dim 4
temp = []
for t in tensores:
    temp.extend(torch.split(t, t.size(4)//2, dim=4))

tensores = temp

for t in tensores:
    print(t.shape)

torch.Size([2, 4, 3, 4, 5])
torch.Size([2, 4, 3, 4, 5])
torch.Size([2, 4, 3, 4, 5])
torch.Size([2, 4, 3, 4, 5])
torch.Size([2, 4, 3, 4, 5])
torch.Size([2, 4, 3, 4, 5])
torch.Size([2, 4, 3, 4, 5])
torch.Size([2, 4, 3, 4, 5])


Clonado y Copiado
========
1. Crear un tensor 1D con valores del 1 al 5, clonarlo (o copiarlo) y demostrar que modificar el tensor clonado no afecta al tensor original.
2. Dado un tensor 2D de forma (3, 3) con valores aleatorios, crear una copia independiente y verificar que tienen diferentes ubicaciones en memoria.
3. Crear un tensor con gradientes habilitados (en PyTorch) o una variable (en TensorFlow), clonarlo y mostrar que el tensor clonado mantiene (o no) el historial de gradientes.
4. Dado un tensor 2D, crear una función que reciba el tensor y devuelva una copia que no comparta memoria con el original, y demostrar que los cambios en la copia no afectan al original.
5. Crear un tensor 3D y realizar una operación de slicing para obtener una subparte. Luego, clonar esa subparte y modificarla, verificando que el tensor original no se ve afectado.
6. Dado un tensor de forma (4, 4), realizar una operación que copie solo los elementos de las esquinas en un nuevo tensor y demostrar que es una copia independiente.
7. Crear una función que, dado un tensor con gradientes habilitados (en PyTorch), realice operaciones que involucren clonados y copiados, y explicar cómo afecta esto al flujo de gradientes.
8. Dado un tensor grande, crear varias copias y demostrar cómo el uso de memoria se ve afectado. Implementar una estrategia para minimizar el uso de memoria utilizando operaciones in situ cuando sea posible.
9. Explicar y demostrar con código la diferencia entre una asignación directa, una clonación y una copia profunda (deep copy) de un tensor, y cómo cada una afecta la relación entre los tensores involucrados.
10. Crear un tensor y utilizar operaciones avanzadas de clonado y copiado para duplicar solo ciertas partes del tensor según una condición específica (por ejemplo, copiar solo los elementos mayores a un umbral) en un nuevo tensor independiente.

Operaciones de Redimensionamiento
=======
1. Crear un tensor 1D con 12 elementos y redimensionarlo a una matriz 2D de forma (3, 4).
2. Dado un tensor de forma (2, 3, 4), utilizar flatten para convertirlo en un tensor 1D.
3. Crear un tensor 2D de forma (4, 5) y agregar una dimensión extra al inicio para obtener un tensor de forma (1, 4, 5).
4. Dado un tensor de forma (batch_size, height, width, channels), reordenar sus dimensiones para convertirlo al formato (batch_size, channels, height, width).
5. Crear un tensor 3D de forma (2, 3, 4) y permutar sus dimensiones para obtener un tensor de forma (4, 2, 3).
6. Dado un tensor 4D de forma (2, 3, 4, 5), redimensionarlo para que tenga forma (6, 4, 5) combinando las dos primeras dimensiones.
7. Crear un tensor de forma (batch_size, channels, height, width), donde batch_size y channels son variables desconocidas en tiempo de ejecución. Aplanar las dimensiones de height y width para obtener un tensor de forma (batch_size, channels, height * width).
8. Dado un tensor 5D de forma (2, 3, 4, 5, 6), reorganizar sus dimensiones para obtener un tensor de forma (4, 2, 6, 3, 5) utilizando una permutación específica.
9. Crear un tensor 2D de forma (m, n), donde m y n son variables, y redimensionarlo a un tensor 3D de forma (m, n, 1) sin cambiar el número total de elementos.
10. Dado un tensor de forma desconocida pero con un número total de elementos divisible por 12, escribir una función que lo redimensione a una forma de (3, 4, -1), dejando que el framework infiera la última dimensión.

# Tensores imágenes

Dado el siguiente código que permite transformar imágenes en tensores y viceversa, realiza las operaciones que hemos hecho con la seta en numpy pero con tensores, sin pasar estos tensores a numpy.

In [ ]:
import torch
from PIL import Image
import torchvision.transforms as transforms
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

def image_to_tensor_pytorch(image_path):
    """
    Carga una imagen desde la ruta especificada y la convierte en un tensor de PyTorch.

    Args:
        image_path (str): Ruta al archivo de imagen.

    Returns:
        torch.Tensor: Tensor que representa la imagen con forma (channels, height, width).
    """
    # Cargar la imagen utilizando PIL
    image = Image.open(image_path).convert('RGB')

    # Definir una transformación que convierte la imagen a tensor y normaliza los valores a [0, 1]
    transform = transforms.ToTensor()

    # Aplicar la transformación
    tensor = transform(image)

    return tensor

def tensor_pytorch_to_image(tensor, save_path=None):
    """
    Convierte un tensor de PyTorch de vuelta a una imagen y la muestra en pantalla.
    Opcionalmente, guarda la imagen en la ruta especificada.

    Args:
        tensor (torch.Tensor): Tensor que representa la imagen con forma (channels, height, width).
        save_path (str, optional): Ruta donde se guardará la imagen. Por defecto es None.

    Returns:
        PIL.Image.Image: Objeto de imagen de PIL.
    """
    # Asegurarse de que el tensor está en CPU y convertirlo a NumPy
    tensor = tensor.cpu()
    image_array = tensor.permute(1, 2, 0).numpy()  # Cambiar a (height, width, channels)

    # Convertir los valores a [0, 255] y tipo uint8
    image_array = np.clip(image_array * 255, 0, 255).astype(np.uint8)

    # Crear una imagen PIL desde el array de NumPy
    image = Image.fromarray(image_array)

    # Mostrar la imagen usando Matplotlib
    plt.imshow(image)
    plt.axis('off')  # Ocultar los ejes
    plt.show()

    # Guardar la imagen si se proporciona una ruta
    if save_path:
        image.save(save_path)
        print(f"Imagen guardada en: {save_path}")

    return image

def image_to_tensor_tensorflow(image_path):
    """
    Carga una imagen desde la ruta especificada y la convierte en un tensor de TensorFlow.

    Args:
        image_path (str): Ruta al archivo de imagen.

    Returns:
        tf.Tensor: Tensor que representa la imagen con forma (height, width, channels).
    """
    # Leer el archivo de imagen
    image_string = tf.io.read_file(image_path)

    # Decodificar la imagen (ajustar el formato según sea JPEG o PNG)
    image = tf.image.decode_image(image_string, channels=3)

    # Convertir la imagen a float32 y escalar los valores de píxeles a [0, 1]
    image = tf.image.convert_image_dtype(image, tf.float32)

    return image


def tensor_tensorflow_to_image(tensor, save_path=None):
    """
    Convierte un tensor de TensorFlow de vuelta a una imagen y la muestra en pantalla.
    Opcionalmente, guarda la imagen en la ruta especificada.

    Args:
        tensor (tf.Tensor): Tensor que representa la imagen con forma (height, width, channels).
        save_path (str, optional): Ruta donde se guardará la imagen. Por defecto es None.

    Returns:
        PIL.Image.Image: Objeto de imagen de PIL.
    """
    # Convertir el tensor a NumPy
    image_array = tensor.numpy()

    # Escalar los valores de [0, 1] a [0, 255] y convertir a uint8
    image_array = np.clip(image_array * 255, 0, 255).astype(np.uint8)

    # Crear una imagen PIL desde el array de NumPy
    image = Image.fromarray(image_array)

    # Mostrar la imagen usando Matplotlib
    plt.imshow(image)
    plt.axis('off')  # Ocultar los ejes
    plt.show()

    # Guardar la imagen si se proporciona una ruta
    if save_path:
        image.save(save_path)
        print(f"Imagen guardada en: {save_path}")

    return image

# Ruta a la imagen
ruta_imagen = 'ruta/a/tu/imagen.jpg'

# Convertir la imagen a tensor pytorch
tensor_imagen = image_to_tensor_pytorch(ruta_imagen)

# Convertir la imagen a tensor tensorflow
tensor_imagen = image_to_tensor_tensorflow(ruta_imagen)


print("Forma del tensor:", tensor_imagen.shape)
print("Tipo de datos:", tensor_imagen.dtype)


# Mostrar la imagen desde el tensor de PyTorch
print("\nMostrando la imagen original desde PyTorch tensor:")
tensor_pytorch_to_image(tensor_imagen)

print("\nMostrando la imagen desde TensorFlow tensor:")
tensor_tensorflow_to_image(tensor_imagen)

# Opcional: Guardar las imágenes 
tensor_pytorch_to_image(tensor_imagen, save_path='seta_pytorch.png')
tensor_tensorflow_to_image(tensor_imagen, save_path='seta_tensorflow.png')

ModuleNotFoundError: No module named 'torchvision'